## os-gaming — preset MangoHud
## Afficher / masquer l'overlay en jeu : Maj droite + F12
## Changer la position : Maj droite + F11

legacy_layout=false
position=top-left
font_size=22
background_alpha=0.40

cpu_temp
cpu_stats
gpu_temp
gpu_stats
gpu_core_clock
gpu_mem_clock
vram
ram
fps
frametime
frame_timing
throttling_status

toggle_hud=Shift_R+F12
toggle_hud_position=Shift_R+F11
